export DEV="/Users/aromia/Creation/Programming"
alias dev="cd /Users/aromia/Creation/Programming;ls"
alias zshconfig="vim ${ZDOTDIR}/.zshrc"
alias touchid="open /etc/pam.d/; echo -n 'auth       sufficient     pam_tid.so' | pbcopy; vim /etc/pam.d/sudo"
alias p10kconfig="vim ~/.config/zsh/.p10k.zsh"
alias powerusage="top -stats pid,command,power -o power"
alias keybr="dev; cd GitHubRepo/keybr.com; open http://localhost:3000; npm start"
alias huaweiyun="echo -n WKZ!T@yBVdG8yba | pbcopy; ssh root@114.115.138.231"
alias clash="export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890"
alias unclash="export https_proxy='' http_proxy='' all_proxy=''"
