alias c="open -a \"Visual Studio Code\" ."
alias vsCpp="code /Users/aromia/Creation/Programming/Cpp/Cpp.code-workspace"
alias vsPy="code /Users/aromia/Creation/Programming/Python/Python.code-workspace"
alias vsLearn="code /Users/aromia/Creation/LearningMaterial/LearningMaterial.code-workspace"
alias vsIo="code /Users/aromia/Creation/Programming/IoT/IoT.code-workspace"
alias vsWeb="code /Users/aromia/Creation/Programming/WebDev/WebDev.code-workspace"
alias vsTex="code /Users/aromia/Creation/Programming/LaTeX/LaTeX.code-workspace"
