[ids]
*

[main]
rightalt = layer(alt_r)
leftshift = layer(shift_l)
capslock = esc
esc = overload(fn, capslock)

[alt_r]
h = left
j = down
k = up
l = right
u = pagedown
i = pageup

[shift_l:S]
space = _

[fn]
# right hand
u = volumedown
i = volumeup
o = mute
j = previoussong
k = playpause
l = nextsong
n = brightnessdown
m = brightnessup
# left hand
q = volumedown
w = volumeup
e = mute
a = previoussong
s = playpause
d = nextsong
z = brightnessdown
x = brightnessup

[alt_r+fn]
h = home
j = C-end
k = C-home
l = end
u = pagedown
i = pageup
