alias pacin="sudo pacman -S"
alias pacun="sudo pacman -R"
alias pacfi="pacman -Ss"
alias pacup="sudo pacman -Syu"
alias pacinfo="pacman -Si"

alias prin="paru -S"
alias prun="paru -R"
alias prfi="paru -Ss"
alias prup="paru -Syu"
alias prinfo="paru -Si"
