export DEV="/Users/aromia/Creation/Programming"
alias dev="cd /Users/aromia/Creation/Programming;ea"
alias zshconfig="nvim $ZDOTDIR"
alias touchid="open /etc/pam.d/; echo -n 'auth       sufficient     pam_tid.so' | pbcopy; vim /etc/pam.d/sudo"
alias p10kconfig="vim ~/.config/zsh/.p10k.zsh"
alias powerusage="top -stats pid,command,power -o power"
alias clash="export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890"
alias unclash="export https_proxy='' http_proxy='' all_proxy=''"
alias fghjkl="fsleep"
alias share="bunx serve ~/Documents/share -p 2305 &"
alias ncmcover="ncmcover /Users/aromia/Downloads"
alias qkd="export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890; \qkd; export https_proxy='' http_proxy='' all_proxy=''"
if [ "$(uname -m)" = "x86_64" ]; then
  alias open="xdg-open"
fi
